spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
logging:
  level:
    org.hibernate.SQL: debug
